### ISSUE TITLE
remove 'rm -rf' from bootstrap process

### ISSUE THREAD

**Issue by damned** [www-thoughtworks-com/hacienda#6]
a bit risky with automatic script running 'rm -rf' - not great if someone downloads gem, runs bootstrap and potentially recursively deletes some of their data...

e.g. if some enters a test repo with space in it?  with an asterisk in it?

**Comment by mmircea16** [comment]
Added this commit to implement the above: https://github.com/www-thoughtworks-com/hacienda/commit/a35efc66e2b170cf5765ce23d9f86b94fd9f7f0e
