### ISSUE TITLE
$filter does not work with 'or' 

### ISSUE THREAD

**Issue by benearlam** [www-thoughtworks-com/hacienda#9]
FilterQueryOption does not implement 'or', it only implements 'and'.

We would like to perform a query like:

https://content-service?$filter=uuid eq 'uuid-1' or eq 'uuid-2'

**Comment by mmircea16** [comment]
+1 Good point! That should easy to implement!

**Comment by mmircea16** [comment]
Implemented here: https://github.com/www-thoughtworks-com/hacienda/commit/ff29b618f73a3bf8cb8bbbf21fdd6f3f0a49b6d5
